### ISSUE TITLE
slash commandes

### ISSUE THREAD

**Issue by Cyanic76** [Pikcsou/Picsou-bot#5]
Vous utilisez le prefix / sauf que dans mon serveur bah y a déjà 1 bot qui utilise les slash commands, ce qui fait que lorsqu'on utilise /help ça renvoie sur le bot en question au lieu du votre.

donc y a moyen de changer le préfix???

*Un peu rapide la fermeture de l'issue :p*

**Comment by Pikcsou** [comment]
Il semblait l'avoir précisé, mais oui. C'est possible de changer le préfixe ; du moment qu'il ne contient pas d'émojis et ne dépasse pas les 3 caractères.

**Comment by Cyanic76** [comment]
et c'est quoi la commande?

**Comment by Pikcsou** [comment]
> et c'est quoi la commande?

/settings prefixe "prefix"

**Comment by Cyanic76** [comment]
Et il est sensé y avoir une réponse de la part du bot?

**Comment by Pikcsou** [comment]
> une réponse de la part du bot

Si la commande a correctement était faite, oui.

**Comment by Cyanic76** [comment]
Ah, bon. Bah j'arrive pas à la faire fonctionner

**Comment by Pikcsou** [comment]
> Ah, bon. Bah j'arrive pas à la faire fonctionner

Si vous le souhaitez, je peut changer directement le préfixe dans la base de donnée.

**Comment by Cyanic76** [comment]
Oui svp

Serveur 622794903675600926
Préfixe p!

**Comment by Pikcsou** [comment]
Voilà ! Le préfixe à correctement était changé !

**Comment by Pikcsou** [comment]
Je viens de remarquer que le bot n'as pas accès au salon où vous exécutez la commande.

**Comment by Cyanic76** [comment]
problème résolu du coup
